---
title: "SSS Map"
author: "Alan Ivory"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
# Load required packages
pacman::p_load(readxl, ggplot2, ggspatial, sf, cowplot)


# Load data
loc_data <- read_excel("locT_Bat_UE.xlsx")
```

## Shapefile
```{r boundary}
florida <- st_read("C:/Users/DrewIvory/OneDrive - University of Florida/Desktop/School/Thesis/SSS_Occupancy/BoundaryMaps/Detailed_Florida_State_Boundary.shp")

floridaC <- st_read("C:/Users/DrewIvory/OneDrive - University of Florida/Desktop/School/Thesis/SSS_Occupancy/BoundaryMaps/tl_2016_12_cousub.shp")

alachua <- floridaC %>%
  dplyr::filter(COUNTYFP == "001")

```

## Convert to sf object

```{r sf}
loc_sf <- st_as_sf(loc_data, coords = c("Long", "Lat"), crs = 4326)
```


## Create Main Map
```{r map}
main_map <- ggplot() +
  geom_sf(data = alachua, fill = NA, color = "black", size = 1) +  # Alachua County outline
  geom_sf(data = loc_sf, color = "black", size = 1.5) +  
  theme_minimal(base_size = 15) +
  theme(
    panel.grid = element_blank(),            
    axis.text = element_text(size = 12),      
    axis.title = element_text(size = 14)      
  ) +
  scale_x_continuous(expand = expansion(mult = c(0.05, 0.05))) +  
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.05))) +  
  annotation_scale(location = "bl", width_hint = 0.2, text_col = "black") +  
  annotation_north_arrow(
    location = "tl",
    which_north = "true",
    style = north_arrow_minimal(text_col = "black", fill = "black"),
  ) +
  labs(title = "", x = "Longitude", y = "Latitude")

```

## Create Inset Map
```{r inset}

inset_map <- ggplot(data = florida) +
  geom_sf(fill = "white", color = "black") +  # Outline of Florida
  geom_sf(data = alachua, fill = "black", color = "black") +  # Highlight Alachua County
  theme_void() +  
  theme(panel.border = element_rect(color = "black", fill = NA))  

```

## Combine Maps
```{r combine}

# main map and inset map
final_map <- ggdraw() +
  draw_plot(main_map) +
  draw_plot(inset_map, x = 0.7, y = 0.7, width = 0.25, height = 0.25)  


print(final_map)


ggsave(
  filename = "site_map_full_screen.png",  
  plot = final_map,
  width = 12,        
  height = 8,        
  dpi = 300           
)
```

### Fixed map
```{r fixed_map}
# Dissolve into a single geometry for Alachua County
alachua_outline <- alachua %>%
  dplyr::summarise(geometry = st_union(geometry))

# Then plot as before
main_map <- ggplot() +
  geom_sf(data = alachua_outline, fill = NA, color = "black", size = 1) +
  geom_sf(data = loc_sf, color = "black", size = 1.5) +  
  theme_minimal(base_size = 15) +
  theme(
    panel.grid = element_blank(),            
    axis.text = element_text(size = 12),      
    axis.title = element_text(size = 14)      
  ) +
  scale_x_continuous(expand = expansion(mult = c(0.05, 0.05))) +  
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.05))) +  
  annotation_scale(location = "bl", width_hint = 0.2, text_col = "black") +  
  annotation_north_arrow(
    location = "tl",
    which_north = "true",
    style = north_arrow_minimal(text_col = "black", fill = "black")
  ) +
  labs(title = "", x = "Longitude", y = "Latitude")

main_map
```

## Include roads
```{r roads}
# Read in TIGER primary roads
roads <- st_read("C:/Users/DrewIvory/OneDrive - University of Florida/Desktop/School/Thesis/SSS_Occupancy/Florida_Roads/tl_2023_12_prisecroads.shp")

# Make sure CRS matches Alachua
roads <- st_transform(roads, st_crs(alachua_outline))

# Optionally clip roads to Alachua County area (with a buffer for display)
roads_clipped <- st_intersection(roads, st_buffer(alachua_outline, dist = 1))  # 10 km buffer

main_map <- ggplot() +
  geom_sf(data = alachua_outline, fill = NA, color = "black", size = 1) +
  geom_sf(data = roads_clipped, color = "grey50", size = 0.8) +  # add roads in red
  geom_sf(data = loc_sf, color = "black", size = 1.5) +  
  theme_minimal(base_size = 15) +
  theme(
    panel.grid = element_blank(),            
    axis.text = element_text(size = 12),      
    axis.title = element_text(size = 14)      
  ) +
  scale_x_continuous(expand = expansion(mult = c(0.05, 0.05))) +  
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.05))) +  
  annotation_scale(location = "bl", width_hint = 0.2, text_col = "black") +  
  annotation_north_arrow(
    location = "tl",
    which_north = "true",
    style = north_arrow_minimal(text_col = "black", fill = "black")
  ) +
  labs(title = "", x = "Longitude", y = "Latitude")

main_map

# main map and inset map
final_map <- ggdraw() +
  draw_plot(main_map) +
  draw_plot(inset_map, x = 0.7, y = 0.7, width = 0.25, height = 0.25)  


print(final_map)

ggsave(
  filename = "site_map_Roads.png",  
  plot = final_map,
  width = 12,        
  height = 8,        
  dpi = 300           
)
```




